repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: .*/migrations/.*
      - id: ruff-format
        exclude: .*/migrations/.*

  - repo: local
    hooks:
      - id: pylint
        name: pylint-django
        entry: pylint
        language: system
        types: [python]
        exclude: .*/migrations/.*
        args: [--rcfile=.pylintrc]
