[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "W", "Q"]

ignore = [
    "B008",
    "E712"
]

[tool.ruff.lint.per-file-ignores]
"**/migrations" = ["E402"]


[tool.ruff.format]
quote-style = "double"